version: "3"

services:
  webserver:
    container_name: service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /home/app/node_modules
      - .:/home/app
    command: "node main.js"
